### ISSUE TITLE
[qase-core-reporter] Auto-created test cases do not have attachments added to the results in Qase TMS

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-javascript#279]
STR:
- install `qase-core-reporter` from https://github.com/qase-tms/qase-javascript/pull/275
- install `cypress-qase-reporter` (~~or `playwright-qase-reporter` - same behavior~~)
- check-in reporter options activated `uploadAttachments` and `sendScreenshot`
- execute spec file (with tests) with qase Id
- execute spec file (with tests) without qase Id

AR:
- for tests with linking qase Id the attachment is added to the results in Qase TMS
- tests without linking to qase Id (auto-created test cases) do not have attachments added to the results in Qase TMS

ER:
- auto created test cases should have a comparison of new test cases, results, and attachment

This behavior is reproduced in `cypress-qase-reporter` ~~and `playwright-qase-reporter`~~

https://user-images.githubusercontent.com/64368690/188906020-da672ffe-8262-40ed-8097-53f1ed949c43.mp4

**Comment by 1ivliev** [comment]
@dimitriharding

**Comment by dimitriharding** [comment]
@1ivliev Thanks for reporting this. It looks like this is an existing limitation of how files are associated with test results for the Cypress reporters. 

Files are linked to test results using the Qase ID, since screenshot information is not included in the test data provided in the `EVENT_TEST_FAIL` event, attachments aren't included when no ID is provided. 

Still I should be able to update the `qase-core-reporter/examples/cypress-reporter` to account for this case. 

---

The issue is reproducible using: https://github.com/qase-tms/qase-javascript/tree/master/qase-cypress. Could you confirm? 

---

For playwright I will have to take a closer look at that one since the path to the screenshot is provided on the test data so wether or not there is an ID we should be able to link screenshots.

**Comment by 1ivliev** [comment]
Yes, I confirm the similar behavior for cypress in this [branch](https://github.com/qase-tms/qase-javascript/tree/master/qase-cypress).
About the playwright, I'll answer later

**Comment by dimitriharding** [comment]
> Sorry, about Playwright. I had broken test data, so I couldn't report the attachment without the `qase` bindings. Not relevant to playwright. Updated the original post.

Thanks for rechecking this.

**Comment by dimitriharding** [comment]
Available for retest

Updated the `cypress-qase-reporter` example to search for a screenshot file in the screenshot folder that matches the test title and includes `(failed)` since that is a pattern for file names with Cypress. 

This search is only done if the `uploadAttachments` options is enabled and the failed test case title does not include a Qase ID (since this case is already accounted for). 

<img width="1050" alt="test run with attachment from non-qase-id screenshot" src="https://user-images.githubusercontent.com/12203794/189257816-d77f128d-a0c5-40cd-b806-21a501dc1798.png">
<img width="1110" alt="uploaded screenshots" src="https://user-images.githubusercontent.com/12203794/189257818-06e58723-1f43-46d1-ad10-57db778c26af.png">

**Comment by 1ivliev** [comment]
@dimitriharding 
I caught a strange behavior. In the config I use the options `"sendScreenshot": true` and `"runComplete": true`.

 - we see a full report on the first pass (using identifiers and the `"sendScreenshot": true` option).
 - on the second pass (without using identifiers and the option `"sendScreenshot": true`), we observe no results and an error in the console:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/64368690/189598523-8597ab02-efaa-408c-b55b-889a38f815ff.png">

- on the third pass (without using the identifier and the option `"sendScreenshot": false`), we observe the results, but without attachment in the `failed` result.

https://user-images.githubusercontent.com/64368690/189596427-8fbfdcaa-c42c-401b-a9d2-9777576909a6.mp4

Could you look at this problem again?

**Comment by dimitriharding** [comment]
@1ivliev My bad, I should have mentioned that `qase-core-reporter` would have needed a rebuild since I made a slight change and replaced that line in your screenshot that is throwing an error since I was experiencing the same. 

Could you try with a new core build and see if that resolves this issue for you?

<img width="1050" alt="update-result-upload-bulk" src="https://user-images.githubusercontent.com/12203794/189655406-7e00f5f1-330d-440e-8fa6-8560dac8bbf5.png">

**Comment by 1ivliev** [comment]
@dimitriharding can you publish the new code in a new commit?

**Comment by dimitriharding** [comment]
Yes, the change was already published with the fix commit that was made for this issue:  https://github.com/qase-tms/qase-javascript/pull/275/commits/e1d9df2135cff758db976bf510b291ca191fdfec

I also confirmed that the new code is on the branch: https://github.com/dimitriharding/qase-javascript/blob/feat/qase-core-reporter/qase-core-reporter/src/result-bulk-detached.js

If after pulling you aren't seeing the new code, maybe remove the `qase-core-reporter/dist` folder and try a rebuild.

**Comment by 1ivliev** [comment]
Hi! My problem has been resolved. Yes, I previously deleted the folder `./dist` and rebuilt `core`. Thank you!
