### ISSUE TITLE
[qase-core-reporter] Warning message about `@typescript-eslint/typescript-estree`

### ISSUE THREAD

**Issue by 1ivliev** [qase-tms/qase-javascript#282]
STR:

- in https://github.com/qase-tms/qase-javascript/pull/275
- execute 
`cd examples/cucumberjs-reporter`(for example)
- execute
`npm run build`

AR:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/64368690/188960034-00d77b0d-77e9-4887-96a4-dc17c500df8c.png">

`WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.`

`You may find that it works just fine, or you may not.`

`SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.1.0`

`YOUR TYPESCRIPT VERSION: 4.6.4`

`Please only submit bug reports when using the officially supported version.`

ER:

let's discuss about this

**Comment by dimitriharding** [comment]
@1ivliev Resolved this issue with all of the sub reporters that were displaying this warning, they were mainly because of `eslintrc.js` being missed for the sub reporters and also needed to updated to the "root" to be true, so it wouldn't try to traverse outside of the reporter folder to find a a next eslintrc to use. 

---

I am seeing the same issue with the `qase-core-reporter`, but it's mainly because of using one of the more updated versions of typescript which the [msw](https://www.npmjs.com/package/msw) requires for installation. And that module is used while unit testing. 

Will have to see what is the best way to resolve this.

**Comment by dimitriharding** [comment]
@1ivliev All dependency issues should be resolved now.

**Comment by 1ivliev** [comment]
Thank you, this problem no longer appears.
